package client

import (
	"bytes"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// calm-poc: given a repository generated by the forge scaffolder — where
// core.hooksPath points at .beads/hooks and the host hook is forge's
// beads->lefthook dispatcher, whose own content carries neither the Beads
// nor the Lefthook signature (those live only in its ".old"/".lefthook"
// chain siblings) — install-hooks must still recognize the dispatcher as a
// known-owner chain and compose automatically, without either escape-hatch
// env var, exactly as it already does for a hook that carries a recognized
// signature directly (see knownOwnerChainSignature and hook_composition_test.go).

// forgeDispatcherScript renders forge's beads->lefthook dispatcher verbatim
// for hookName, matching the shape produced by forge's
// repairBeadsHookChain.
func forgeDispatcherScript(hookName string) string {
	return "#!/usr/bin/env bash\n" +
		"set -euo pipefail\n" +
		"\n" +
		"script_dir=\"$(CDPATH= cd -- \"$(dirname \"$0\")\" && pwd)\"\n" +
		"\"$script_dir/" + hookName + ".old\" \"$@\"\n" +
		"exec \"$script_dir/" + hookName + ".lefthook\" \"$@\"\n"
}

// forgeOldSiblingScript renders the ".old" chain sibling: the beads hook
// forge preserved verbatim under lefthook's clobber-rename convention. It
// carries the version-independent Beads signature and, when
// $COMPOSITION_LOG is set, records that it ran.
func forgeOldSiblingScript() string {
	return "#!/usr/bin/env bash\n" +
		"# --- BEGIN BEADS INTEGRATION v1.0.3 ---\n" +
		"if [ -n \"${COMPOSITION_LOG:-}\" ]; then\n" +
		"  echo beads >> \"$COMPOSITION_LOG\"\n" +
		"fi\n" +
		"# --- END BEADS INTEGRATION v1.0.3 ---\n"
}

// forgeLefthookSiblingScript renders the ".lefthook" chain sibling: forge's
// rename target for lefthook's own generated shim. It carries the
// "lefthook run" invocation-form signature and, when $COMPOSITION_LOG is
// set, records that it ran.
func forgeLefthookSiblingScript() string {
	return "#!/usr/bin/env bash\n" +
		"# generated by lefthook install; invokes: lefthook run \"$1\"\n" +
		"if [ -n \"${COMPOSITION_LOG:-}\" ]; then\n" +
		"  echo lefthook >> \"$COMPOSITION_LOG\"\n" +
		"fi\n" +
		"exit 0\n"
}

// seedForgeDispatcherChain writes the exact trio forge's
// repairBeadsHookChain leaves behind for hookName under hooksDir: the
// dispatcher itself plus its ".old" (Beads) and ".lefthook" (Lefthook)
// chain siblings, all executable.
func seedForgeDispatcherChain(t *testing.T, hooksDir, hookName string) {
	t.Helper()
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		t.Fatalf("mkdir hooks dir: %v", err)
	}
	files := map[string]string{
		hookName:               forgeDispatcherScript(hookName),
		hookName + ".old":      forgeOldSiblingScript(),
		hookName + ".lefthook": forgeLefthookSiblingScript(),
	}
	for name, content := range files {
		if err := os.WriteFile(filepath.Join(hooksDir, name), []byte(content), 0o755); err != nil {
			t.Fatalf("seed %s: %v", name, err)
		}
	}
}

// initForgeStyleRepo creates a real git repository with core.hooksPath
// redirected to .beads/hooks, mirroring what `bd init` leaves behind in a
// forge-generated repository (see
// TestRunInstallHooksComposesInRedirectedCoreHooksPath for the same
// redirect fixture without a forge dispatcher chain layered on top).
func initForgeStyleRepo(t *testing.T, repo string) string {
	t.Helper()
	runGitClientTest(t, repo, "init")
	runGitClientTest(t, repo, "config", "core.hooksPath", ".beads/hooks")
	return filepath.Join(repo, ".beads", "hooks")
}

func TestInstallHooksComposesForgeDispatcherChain(t *testing.T) {
	repo := t.TempDir()
	hooksDir := initForgeStyleRepo(t, repo)
	seedForgeDispatcherChain(t, hooksDir, "pre-commit")
	seedForgeDispatcherChain(t, hooksDir, "pre-push")

	t.Setenv("AGENT_FITNESS_FUNCTIONS_HOOK_APPEND", "")
	t.Setenv("AGENT_FITNESS_FUNCTIONS_HOOK_OVERWRITE", "")

	oldBefore := map[string][]byte{}
	lefthookBefore := map[string][]byte{}
	for _, hookName := range []string{"pre-commit", "pre-push"} {
		var err error
		oldBefore[hookName], err = os.ReadFile(filepath.Join(hooksDir, hookName+".old"))
		if err != nil {
			t.Fatalf("read seeded %s.old: %v", hookName, err)
		}
		lefthookBefore[hookName], err = os.ReadFile(filepath.Join(hooksDir, hookName+".lefthook"))
		if err != nil {
			t.Fatalf("read seeded %s.lefthook: %v", hookName, err)
		}
	}

	var stdout, stderr bytes.Buffer
	if err := RunInstallHooks([]string{repo}, &stdout, &stderr); err != nil {
		t.Fatalf("RunInstallHooks refused a forge dispatcher chain without escape hatches: %v\nstderr=%s", err, stderr.String())
	}

	for _, hookName := range []string{"pre-commit", "pre-push"} {
		hostPath := filepath.Join(hooksDir, hookName)
		content, err := os.ReadFile(hostPath)
		if err != nil {
			t.Fatalf("read composed %s: %v", hookName, err)
		}
		text := string(content)

		sidecarMarker := "agent-fitness-functions " + hookName + " hook (sidecar)"
		if count := strings.Count(text, sidecarMarker); count != 1 {
			t.Fatalf("%s: sidecar marker appears %d times, want exactly 1:\n%s", hookName, count, text)
		}
		sidecarCall := "agent-fitness-functions-" + hookName
		if count := strings.Count(text, sidecarCall); count != 1 {
			t.Fatalf("%s: delegated sidecar call appears %d times, want exactly 1:\n%s", hookName, count, text)
		}

		execLine := "exec \"$script_dir/" + hookName + ".lefthook\""
		execIndex := strings.Index(text, execLine)
		sidecarIndex := strings.Index(text, sidecarCall)
		if execIndex == -1 || sidecarIndex == -1 || sidecarIndex > execIndex {
			t.Fatalf("%s: delegated call must land before the terminal exec (sidecar at %d, exec at %d):\n%s", hookName, sidecarIndex, execIndex, text)
		}

		oldContent, err := os.ReadFile(filepath.Join(hooksDir, hookName+".old"))
		if err != nil {
			t.Fatalf("read %s.old after compose: %v", hookName, err)
		}
		if !bytes.Equal(oldContent, oldBefore[hookName]) {
			t.Fatalf("%s.old was modified during composition:\nbefore:\n%s\nafter:\n%s", hookName, oldBefore[hookName], oldContent)
		}
		lefthookContent, err := os.ReadFile(filepath.Join(hooksDir, hookName+".lefthook"))
		if err != nil {
			t.Fatalf("read %s.lefthook after compose: %v", hookName, err)
		}
		if !bytes.Equal(lefthookContent, lefthookBefore[hookName]) {
			t.Fatalf("%s.lefthook was modified during composition:\nbefore:\n%s\nafter:\n%s", hookName, lefthookBefore[hookName], lefthookContent)
		}
	}

	dotGitHooks := filepath.Join(repo, ".git", "hooks")
	if entries, err := os.ReadDir(dotGitHooks); err == nil {
		for _, entry := range entries {
			// git init itself seeds .git/hooks with *.sample templates;
			// only a non-sample file would indicate install-hooks wrote
			// there despite the core.hooksPath redirect.
			if !strings.HasSuffix(entry.Name(), ".sample") {
				t.Fatalf(".git/hooks received content despite core.hooksPath redirect: %s", entry.Name())
			}
		}
	} else if !os.IsNotExist(err) {
		t.Fatalf("stat .git/hooks: %v", err)
	}

	before, err := snapshotHooksDir(hooksDir)
	if err != nil {
		t.Fatalf("snapshot hooks dir: %v", err)
	}
	if err := RunInstallHooks([]string{repo}, &stdout, &stderr); err != nil {
		t.Fatalf("second RunInstallHooks: %v\nstderr=%s", err, stderr.String())
	}
	after, err := snapshotHooksDir(hooksDir)
	if err != nil {
		t.Fatalf("snapshot hooks dir after rerun: %v", err)
	}
	if before != after {
		t.Fatalf("repeated onboarding changed the forge dispatcher chain:\nbefore:\n%s\nafter:\n%s", before, after)
	}
}

func TestComposedForgeChainOrderingAndFailurePropagation(t *testing.T) {
	repo := t.TempDir()
	hooksDir := initForgeStyleRepo(t, repo)
	seedForgeDispatcherChain(t, hooksDir, "pre-commit")

	t.Setenv("AGENT_FITNESS_FUNCTIONS_HOOK_APPEND", "")
	t.Setenv("AGENT_FITNESS_FUNCTIONS_HOOK_OVERWRITE", "")
	var stdout, stderr bytes.Buffer
	if err := RunInstallHooks([]string{repo}, &stdout, &stderr); err != nil {
		t.Fatalf("RunInstallHooks: %v\nstderr=%s", err, stderr.String())
	}

	sidecarPath := filepath.Join(hooksDir, "agent-fitness-functions-pre-commit")
	sidecarStub := "#!/usr/bin/env bash\necho agent >> \"$COMPOSITION_LOG\"\nexit \"${SIDECAR_EXIT:-0}\"\n"
	if err := os.WriteFile(sidecarPath, []byte(sidecarStub), 0o755); err != nil {
		t.Fatalf("stub sidecar: %v", err)
	}

	hostHook := filepath.Join(hooksDir, "pre-commit")
	logPath := filepath.Join(t.TempDir(), "composition.log")

	run := func(sidecarExit string) (string, error) {
		if err := os.RemoveAll(logPath); err != nil {
			t.Fatalf("reset log: %v", err)
		}
		command := exec.Command("bash", hostHook)
		command.Dir = repo
		command.Env = append(os.Environ(),
			"COMPOSITION_LOG="+logPath,
			"SIDECAR_EXIT="+sidecarExit,
		)
		runErr := command.Run()
		content, readErr := os.ReadFile(logPath)
		if readErr != nil {
			t.Fatalf("read composition log: %v", readErr)
		}
		return string(content), runErr
	}

	log, err := run("0")
	if err != nil {
		t.Fatalf("composed forge chain failed on the success path: %v\nlog:\n%s", err, log)
	}
	lines := strings.Fields(log)
	wantOrder := []string{"beads", "agent", "lefthook"}
	if len(lines) != len(wantOrder) {
		t.Fatalf("log lines = %v, want exactly %v", lines, wantOrder)
	}
	for i, want := range wantOrder {
		if lines[i] != want {
			t.Fatalf("log order = %v, want %v", lines, wantOrder)
		}
	}

	failLog, err := run("7")
	if err == nil {
		t.Fatal("composed forge chain exited zero although the governance sidecar failed")
	}
	if strings.Contains(failLog, "lefthook") {
		t.Fatalf("lefthook stage ran after sidecar failure, want short-circuit under set -e:\n%s", failLog)
	}
}

func TestInstallHooksStillRefusesUnrelatedHookWithStaleChainSiblings(t *testing.T) {
	repo := t.TempDir()
	runGitClientTest(t, repo, "init")
	hooksDir := filepath.Join(repo, ".git", "hooks")
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		t.Fatalf("mkdir hooks: %v", err)
	}

	hostHook := filepath.Join(hooksDir, "pre-commit")
	handWritten := "#!/bin/sh\necho custom\n"
	if err := os.WriteFile(hostHook, []byte(handWritten), 0o755); err != nil {
		t.Fatalf("write hand-written hook: %v", err)
	}
	// A stray ".old" sibling carrying the Beads signature, but the host hook
	// never references it by name, so it must not relax refuse-by-default.
	if err := os.WriteFile(filepath.Join(hooksDir, "pre-commit.old"), []byte(forgeOldSiblingScript()), 0o755); err != nil {
		t.Fatalf("write stray .old sibling: %v", err)
	}

	var stdout, stderr bytes.Buffer
	err := RunInstallHooks([]string{repo}, &stdout, &stderr)
	if err == nil {
		t.Fatalf("RunInstallHooks succeeded despite an unrelated hand-written hook, want refusal; stdout=%s", stdout.String())
	}
	if !strings.Contains(stderr.String(), "AGENT_FITNESS_FUNCTIONS_HOOK_APPEND=1") {
		t.Fatalf("stderr = %s, want mention of AGENT_FITNESS_FUNCTIONS_HOOK_APPEND=1", stderr.String())
	}

	content, err := os.ReadFile(hostHook)
	if err != nil {
		t.Fatalf("read hook after refusal: %v", err)
	}
	if string(content) != handWritten {
		t.Fatalf("hand-written hook bytes changed:\nbefore:\n%s\nafter:\n%s", handWritten, content)
	}
}

// --- WP2: forge-managed settings.json (ADR-0006 "forge interop") ---
//
// A repo generated by the forge scaffolder ships a .claude/settings.json
// that forge's own `forge upgrade` command overwrites wholesale on every
// managed-file sync (a forge-generated repo prompts `forge upgrade --check`
// at every Claude session start via its SessionStart chain), silently
// destroying any PreToolUse entry install-hooks lands there. Detection keys
// on the literal substrings "forge upgrade" / "forge sync-allowlist" WITH
// the space, so forge's own hyphenated command names ("forge-guard",
// "forge-session-start" — see TestInstallHooksPreservesForgeSessionStartSettings
// in hook_composition_test.go, which must keep exercising the
// settings.json-targeting path unchanged) never trip it. When forge
// management is detected, install-hooks targets .claude/settings.local.json
// instead, which forge's allowlist reconciler only ever rewrites between its
// own "// BEGIN/END FORGE ALLOW" marker strings inside permissions.allow,
// leaving any PreToolUse entries there untouched.

// forgeTemplateSettingsJSON renders the shape forge's `init`/`upgrade`
// commands leave at .claude/settings.json: a Bash PreToolUse guard plus a
// SessionStart chain whose last two commands run `forge sync-allowlist
// --check` and `forge upgrade --check`.
const forgeTemplateSettingsJSON = `{
  "enabledPlugins": {},
  "hooks": {
    "PreToolUse": [
      { "matcher": "Bash", "hooks": [ { "type": "command", "command": "./.claude/hooks/guard" } ] }
    ],
    "SessionStart": [
      { "matcher": "", "hooks": [
        { "type": "command", "command": "bd prime || true" },
        { "type": "command", "command": "instill sync || true" },
        { "type": "command", "command": "command -v forge >/dev/null 2>&1 && forge sync-allowlist --check || true" },
        { "type": "command", "command": "command -v forge >/dev/null 2>&1 && forge upgrade --check || true" }
      ] }
    ]
  }
}
`

// forgeTemplateSettingsJSONWithPreClobberGuard is forgeTemplateSettingsJSON
// plus a second PreToolUse entry shaped like a pre-fix install-hooks run: one
// that landed a product git-guard entry directly in settings.json before
// forge-detection existed, and which forge's next `upgrade` would silently
// destroy.
const forgeTemplateSettingsJSONWithPreClobberGuard = `{
  "enabledPlugins": {},
  "hooks": {
    "PreToolUse": [
      { "matcher": "Bash", "hooks": [ { "type": "command", "command": "./.claude/hooks/guard" } ] },
      { "matcher": "Bash", "hooks": [ { "type": "command", "command": "/repo/.git/hooks/agent-fitness-functions-git-guard" } ] }
    ],
    "SessionStart": [
      { "matcher": "", "hooks": [
        { "type": "command", "command": "bd prime || true" },
        { "type": "command", "command": "instill sync || true" },
        { "type": "command", "command": "command -v forge >/dev/null 2>&1 && forge sync-allowlist --check || true" },
        { "type": "command", "command": "command -v forge >/dev/null 2>&1 && forge upgrade --check || true" }
      ] }
    ]
  }
}
`

// forgeTemplateSettingsLocalJSON renders a settings.local.json carrying
// forge's allowlist reconciler markers: forge's sync-allowlist rewrites only
// the JSON string elements between "// BEGIN FORGE ALLOW v:1" and
// "// END FORGE ALLOW" inside permissions.allow, leaving everything else in
// the file — including any PreToolUse hooks section install-hooks adds —
// untouched.
const forgeTemplateSettingsLocalJSON = `{
  "permissions": {
    "allow": [
      "Bash(ls:*)",
      "// BEGIN FORGE ALLOW v:1",
      "Bash(git status:*)",
      "Bash(git diff:*)",
      "// END FORGE ALLOW"
    ]
  }
}
`

func seedForgeClaudeSettings(t *testing.T, claudeDir, settingsJSON, settingsLocalJSON string) {
	t.Helper()
	if err := os.MkdirAll(claudeDir, 0o755); err != nil {
		t.Fatalf("mkdir .claude: %v", err)
	}
	if settingsJSON != "" {
		if err := os.WriteFile(filepath.Join(claudeDir, "settings.json"), []byte(settingsJSON), 0o644); err != nil {
			t.Fatalf("seed settings.json: %v", err)
		}
	}
	if settingsLocalJSON != "" {
		if err := os.WriteFile(filepath.Join(claudeDir, "settings.local.json"), []byte(settingsLocalJSON), 0o644); err != nil {
			t.Fatalf("seed settings.local.json: %v", err)
		}
	}
}

func TestInstallHooksWritesSettingsLocalInForgeManagedRepo(t *testing.T) {
	repo := t.TempDir()
	useDeterministicGitClientTest(t, repo)
	claudeDir := filepath.Join(repo, ".claude")
	seedForgeClaudeSettings(t, claudeDir, forgeTemplateSettingsJSON, forgeTemplateSettingsLocalJSON)

	settingsJSONPath := filepath.Join(claudeDir, "settings.json")
	settingsLocalPath := filepath.Join(claudeDir, "settings.local.json")

	var stdout, stderr bytes.Buffer
	if err := RunInstallHooks([]string{repo}, &stdout, &stderr); err != nil {
		t.Fatalf("RunInstallHooks: %v\nstderr=%s", err, stderr.String())
	}

	settingsJSONAfter, err := os.ReadFile(settingsJSONPath)
	if err != nil {
		t.Fatalf("read settings.json: %v", err)
	}
	if string(settingsJSONAfter) != forgeTemplateSettingsJSON {
		t.Fatalf("forge-owned settings.json was modified:\nbefore:\n%s\nafter:\n%s", forgeTemplateSettingsJSON, settingsJSONAfter)
	}

	settingsLocalAfter, err := os.ReadFile(settingsLocalPath)
	if err != nil {
		t.Fatalf("read settings.local.json: %v", err)
	}
	localText := string(settingsLocalAfter)
	for _, marker := range []string{gitGuardName, agentHookName} {
		if count := strings.Count(localText, marker); count != 1 {
			t.Fatalf("product marker %q appears %d times in settings.local.json, want exactly 1:\n%s", marker, count, localText)
		}
	}
	for _, marker := range []string{"// BEGIN FORGE ALLOW v:1", "// END FORGE ALLOW"} {
		if count := strings.Count(localText, marker); count != 1 {
			t.Fatalf("FORGE ALLOW marker %q appears %d times in settings.local.json, want exactly 1:\n%s", marker, count, localText)
		}
	}

	if err := RunInstallHooks([]string{repo}, &stdout, &stderr); err != nil {
		t.Fatalf("second RunInstallHooks: %v\nstderr=%s", err, stderr.String())
	}
	settingsJSONSecond, err := os.ReadFile(settingsJSONPath)
	if err != nil {
		t.Fatalf("read settings.json after rerun: %v", err)
	}
	if string(settingsJSONSecond) != forgeTemplateSettingsJSON {
		t.Fatalf("forge-owned settings.json changed on rerun:\nbefore:\n%s\nafter:\n%s", forgeTemplateSettingsJSON, settingsJSONSecond)
	}
	settingsLocalSecond, err := os.ReadFile(settingsLocalPath)
	if err != nil {
		t.Fatalf("read settings.local.json after rerun: %v", err)
	}
	if !bytes.Equal(settingsLocalAfter, settingsLocalSecond) {
		t.Fatalf("settings.local.json changed on rerun (not idempotent):\nbefore:\n%s\nafter:\n%s", settingsLocalAfter, settingsLocalSecond)
	}
}

func TestInstallHooksMovesPreClobberEntriesOutOfForgeSettingsJSON(t *testing.T) {
	repo := t.TempDir()
	useDeterministicGitClientTest(t, repo)
	claudeDir := filepath.Join(repo, ".claude")
	seedForgeClaudeSettings(t, claudeDir, forgeTemplateSettingsJSONWithPreClobberGuard, "")

	settingsJSONPath := filepath.Join(claudeDir, "settings.json")
	settingsLocalPath := filepath.Join(claudeDir, "settings.local.json")

	var stdout, stderr bytes.Buffer
	if err := RunInstallHooks([]string{repo}, &stdout, &stderr); err != nil {
		t.Fatalf("RunInstallHooks: %v\nstderr=%s", err, stderr.String())
	}

	settingsJSONAfter, err := os.ReadFile(settingsJSONPath)
	if err != nil {
		t.Fatalf("read settings.json: %v", err)
	}
	jsonText := string(settingsJSONAfter)
	if strings.Contains(jsonText, gitGuardName) {
		t.Fatalf("pre-clobber product entry was not removed from forge settings.json:\n%s", jsonText)
	}
	for _, preserved := range []string{"./.claude/hooks/guard", "forge sync-allowlist --check", "forge upgrade --check"} {
		if count := strings.Count(jsonText, preserved); count != 1 {
			t.Fatalf("forge's own entry %q missing/duplicated in settings.json, want exactly 1, got %d:\n%s", preserved, count, jsonText)
		}
	}
	var parsed map[string]any
	if err := json.Unmarshal(settingsJSONAfter, &parsed); err != nil {
		t.Fatalf("settings.json is no longer valid JSON after removal: %v\n%s", err, jsonText)
	}

	settingsLocalAfter, err := os.ReadFile(settingsLocalPath)
	if err != nil {
		t.Fatalf("read settings.local.json: %v", err)
	}
	localText := string(settingsLocalAfter)
	if count := strings.Count(localText, gitGuardName); count != 1 {
		t.Fatalf("product git-guard entry appears %d times in settings.local.json, want exactly 1:\n%s", count, localText)
	}
}
